import "@/styles/globals.css";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body
        className={`${process.env.DEVELOPMENT === "true" && "debug-screens"} ${
          inter.className
        }`}
      >
        {children}
      </body>
    </html>
  );
}
